/**
 * PPProtectedRoute — route guard for PP Subscriber Portal pages.
 *
 * Reads the PP session via GET /api/pp/me.  If the user is not authenticated
 * as a PP subscriber they are redirected to /pp/login.  CRM-only users (who
 * use Replit OIDC sessions, not PP sessions) will also be redirected because
 * their session_type is not 'pp'.
 */
import { useEffect, useState } from 'react';
import { Loader2 } from 'lucide-react';

export interface PPUser {
  id: string;
  email: string | null;
  firstName: string | null;
  lastName: string | null;
  profileImageUrl: string | null;
  companyId: string;
  emailVerified: boolean;
}

export interface PPCompany {
  id: string;
  name: string;
  ppTier: string;
  logoUrl: string | null;
  /** Fresh short-lived signed URL generated by the server — use for preview only. */
  logoSignedUrl: string | null;
  /** Market type set at registration: 'retail' | 'insurance' | 'retail_insurance' */
  workType: string | null;
  /** Trade types set at registration, e.g. ['roofing', 'siding'] */
  tradeTypes: string[] | null;
}

export interface PPMeResponse {
  user: PPUser;
  company: PPCompany;
}

interface PPProtectedRouteProps {
  children: React.ReactNode;
}

export function PPProtectedRoute({ children }: PPProtectedRouteProps) {
  const [status, setStatus] = useState<'loading' | 'authed' | 'unauthed'>('loading');

  useEffect(() => {
    fetch('/api/pp/me', { credentials: 'include' })
      .then((r) => {
        if (r.ok) {
          setStatus('authed');
        } else {
          setStatus('unauthed');
        }
      })
      .catch(() => setStatus('unauthed'));
  }, []);

  if (status === 'loading') {
    return (
      <div className="min-h-screen flex items-center justify-center bg-zinc-950">
        <Loader2 className="h-8 w-8 animate-spin text-orange-500" />
      </div>
    );
  }

  if (status === 'unauthed') {
    window.location.href = '/rooftrax-web/pp/login';
    return null;
  }

  return <>{children}</>;
}
