/**
 * Per-section AI generation for the claim pipeline (Task #122).
 *
 * This module is intentionally DB-free. Callers load all required data
 * from the DB and pass it in. The route handler owns the DB access and
 * the upsert back to claim_sections.
 */

import { ai as geminiAi } from '@workspace/integrations-gemini-ai';
import sanitizeHtml from 'sanitize-html';
import {
  CONTRACTOR_LANE_POLICY,
  lintReportFragments,
  type LintResult,
  type LintFragmentInput,
} from './contentPolicy';
import {
  extractRap,
  computeRapScorecard,
  rapScorecardBriefLines,
} from './rapScorecard';
import {
  extractVap,
  computeVapScorecard,
  vapScorecardBriefLines,
} from './vapScorecard';
import { extractAsp, computeAspScorecard, aspScorecardBriefLines } from './aspScorecard';
import type { StoredRepairabilityAssessment, ClaimSectionType } from '@workspace/db';
import { DETERMINATION_LABELS, RAP_WARRANTED_LABELS } from './repairabilityRules';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Sections generated by the AI pipeline (excluding captions which has its
 * own dedicated route and lifecycle).
 */
export const GENERATABLE_SECTION_TYPES: readonly ClaimSectionType[] = [
  'findings',
  'causation',
  'detriment_application',
  'rap_narrative',
  'estimate_justifications',
  'summary_of_findings',
  'closing_statement',
];
export type GeneratableSectionType = Extract<
  ClaimSectionType,
  | 'findings'
  | 'causation'
  | 'detriment_application'
  | 'rap_narrative'
  | 'estimate_justifications'
  | 'summary_of_findings'
  | 'closing_statement'
>;

/**
 * Sections that cannot be generated until ALL upstream sections are approved
 * or locked (DAG enforcement).
 */
export const DAG_LAST_SECTION_TYPES: ReadonlySet<ClaimSectionType> = new Set<ClaimSectionType>([
  'summary_of_findings',
  'closing_statement',
]);

/**
 * Upstream sections that DAG-last sections depend on.
 */
export const DAG_UPSTREAM_SECTION_TYPES: readonly ClaimSectionType[] = [
  'findings',
  'causation',
  'detriment_application',
  'rap_narrative',
  'estimate_justifications',
];

// ---------------------------------------------------------------------------
// Field condition set — maps field record facts to condition code strings
// used for applicability filtering of detriment entries.
// ---------------------------------------------------------------------------

export function buildFieldConditionSet(
  inspection: Record<string, unknown>,
  children: {
    testSquares?: { id?: string }[];
    damageInstances?: { id?: string; slopeId?: string | null; instanceType?: string | null }[];
    slopes?: { id?: string; damagePresent?: boolean | null; materialType?: string | null }[];
    sidingFacets?: { wrbPresent?: boolean | null; damaged?: boolean | null }[];
  },
): Set<string> {
  const conditions = new Set<string>();

  if (inspection.roofDamageFound) conditions.add('roof_damage_present');
  if (inspection.sidingDamageFound) conditions.add('siding_damage_present');
  if (inspection.interiorDamageFound) conditions.add('interior_damage_present');
  if (inspection.collateralDamageFound) conditions.add('collateral_damage_present');

  const storm = inspection.stormConfirmedRef as { type?: string } | null;
  if (storm?.type === 'hail') conditions.add('hail_peril');
  if (storm?.type === 'wind') conditions.add('wind_peril');
  if (storm?.type === 'tornado') conditions.add('tornado_peril');

  const tr = inspection.temporaryRepairs as
    | { performed?: boolean; openings?: boolean }
    | null;
  if (tr?.performed) conditions.add('mitigation_performed');
  if (tr?.openings) conditions.add('created_opening');

  const ra = inspection.repairabilityAssessment as StoredRepairabilityAssessment | null;
  if (ra) {
    if (ra.version === 3) {
      const v3 = ra as unknown as { warranted?: string; systems?: string[] };
      if (v3.warranted === 'yes') conditions.add('rap_warranted');
      else conditions.add('rap_not_warranted');
    }
    const rapData = extractRap(ra);
    if (rapData) {
      const selMode = rapData.selection?.mode ?? null;
      if (selMode === 'fallback_slope') conditions.add('rap_fallback_slope');
      if (selMode === 'damaged_target') conditions.add('rap_damaged_target');
    }
  }

  if ((children.testSquares ?? []).length > 0) conditions.add('test_squares_present');
  if ((children.damageInstances ?? []).length > 0) conditions.add('damage_instances_present');

  const slopeMaterials = (children.slopes ?? [])
    .map((s) => (s.materialType ?? '').toLowerCase());
  if (slopeMaterials.some((m) => m.includes('asphalt') || m.includes('shingle')))
    conditions.add('asphalt_shingle_material');
  if (slopeMaterials.some((m) => m.includes('metal'))) conditions.add('metal_material');
  if (slopeMaterials.some((m) => m.includes('tile'))) conditions.add('tile_material');

  const estimate = inspection.estimate as { lines?: Array<{ description?: string; categoryCode?: string }> } | null;
  const hasDeck = estimate?.lines?.some(
    (l) =>
      (l.description ?? '').toLowerCase().includes('deck') ||
      (l.categoryCode ?? '').toLowerCase().includes('deck'),
  );
  if (hasDeck) conditions.add('deck_replacement_in_scope');

  if (inspection.interiorDamageFound) conditions.add('interior_scope_present');

  const sidingFacets = children.sidingFacets ?? [];
  if (sidingFacets.some((facet) => facet.wrbPresent === false)) {
    conditions.add('wrb_absent');
  } else if (sidingFacets.length > 0 && sidingFacets.every((facet) => facet.wrbPresent === true)) {
    conditions.add('wrb_present');
  } else if (sidingFacets.some((facet) => facet.damaged === true && facet.wrbPresent == null)) {
    conditions.add('wrb_undetermined');
  }

  const pp = inspection.propertyProfile as
    | { structureType?: string; garageAttached?: boolean }
    | null;
  if (pp?.garageAttached) conditions.add('garage_attached');

  return conditions;
}

/**
 * Applicability gate — filter detriment entries to those whose
 * `applicabilityConditions` are ALL present in the field record condition set.
 * This is a code check, not a prompt instruction.
 */
export function filterDetrimentEntries<T extends { applicabilityConditions: unknown }>(
  entries: T[],
  conditionSet: Set<string>,
): T[] {
  return entries.filter((entry) => {
    const conditions = (entry.applicabilityConditions as string[] | null) ?? [];
    if (conditions.length === 0) return true; // no conditions = universal applicability
    return conditions.every((c) => conditionSet.has(c));
  });
}

// ---------------------------------------------------------------------------
// HTML sanitiser for AI-generated section fragments
// ---------------------------------------------------------------------------
// <a> and <img> are intentionally excluded — section content is LLM output,
// not user-controlled HTML.  External links and embeds must not be injected.
// For user-supplied templates (which allow <a>/<img>), use sanitizeTemplateHtml
// from lib/htmlSanitize.ts instead.
// ---------------------------------------------------------------------------

function sanitizeSectionHtml(raw: string): string {
  return sanitizeHtml(raw, {
    allowedTags: [
      'h2', 'h3', 'h4',
      'p', 'br', 'strong', 'em', 'b', 'i',
      'ul', 'ol', 'li',
      'table', 'thead', 'tbody', 'tfoot', 'tr', 'th', 'td',
      'span', 'div', 'section',
    ],
    allowedAttributes: {
      '*': ['class', 'id', 'style'],
      'td': ['colspan', 'rowspan'],
      'th': ['colspan', 'rowspan', 'scope'],
    },
    allowedStyles: {
      '*': {
        color: [/^[a-zA-Z0-9#(), .%]+$/],
        'background-color': [/^[a-zA-Z0-9#(), .%]+$/],
        'font-size': [/^[\d.]+(%|px|em|rem|pt)$/],
        'font-weight': [/^(bold|normal|\d+)$/],
        'text-align': [/^(left|right|center|justify)$/],
        padding: [/^[\d. px%]+$/],
        margin: [/^[\d. px%]+$/],
        border: [/^[\d. pxsolid#a-zA-Z]+$/],
        'border-radius': [/^[\d.]+(%|px|em|rem)$/],
        opacity: [/^[\d.]+$/],
        display: [/^(block|inline|flex|grid|table|table-row|table-cell|none)$/],
        'vertical-align': [/^(top|middle|bottom|baseline)$/],
      },
    },
    disallowedTagsMode: 'discard',
  });
}

// ---------------------------------------------------------------------------
// Brief builder — compact text summary of the field record
// ---------------------------------------------------------------------------

function buildFieldBrief(
  inspection: Record<string, unknown>,
  children: {
    slopes?: Array<{
      label: string;
      areaSqft?: number | null;
      materialType?: string | null;
      damagePresent?: boolean | null;
      damageType?: string | null;
      pitchRise?: number | null;
      pitchRun?: number | null;
    }>;
    sidingFacets?: Array<{ label?: string; damageType?: string | null; damaged?: boolean | null; wrbPresent?: boolean | null }>;
    damageInstances?: Array<{
      slopeId?: string | null;
      instanceType?: string | null;
      severityCategory?: string | null;
    }>;
    testSquares?: Array<{ label?: string }>;
    testSquareHits?: Array<{ hitType?: string | null }>;
    products?: Array<{
      brand?: string | null;
      productLine?: string | null;
      identificationMethod?: string | null;
      itelSampleRef?: string | null;
    }>;
    interiorObservations?: Array<{ location?: string; description?: string }>;
  },
): string {
  const lines: string[] = [];

  lines.push(`PROPERTY: ${inspection.insuredName ?? 'Unknown'}`);
  if (inspection.address) lines.push(`ADDRESS: ${inspection.address}`);
  if (inspection.claimNumber) lines.push(`CLAIM #: ${inspection.claimNumber}`);
  if (inspection.dateOfLoss) lines.push(`DATE OF LOSS: ${inspection.dateOfLoss}`);

  const storm = inspection.stormConfirmedRef as {
    type?: string;
    date?: string;
    hailSize?: number | null;
    windSpeed?: number | null;
    description?: string | null;
  } | null;
  if (storm) {
    lines.push(`STORM: ${storm.type ?? 'unknown'} on ${storm.date ?? 'unknown date'}`);
    if (storm.hailSize) lines.push(`  Hail size: ${storm.hailSize}"`);
    if (storm.windSpeed) lines.push(`  Wind speed: ${storm.windSpeed} mph`);
  }

  lines.push('');
  lines.push('DAMAGE FLAGS:');
  lines.push(`  Roof: ${inspection.roofDamageFound ? 'YES' : 'no'}`);
  lines.push(`  Siding: ${inspection.sidingDamageFound ? 'YES' : 'no'}`);
  lines.push(`  Collateral: ${inspection.collateralDamageFound ? 'YES' : 'no'}`);
  lines.push(`  Interior: ${inspection.interiorDamageFound ? 'YES' : 'no'}`);

  const slopes = children.slopes ?? [];
  if (slopes.length > 0) {
    lines.push('');
    lines.push('ROOF FACETS:');
    for (const s of slopes) {
      const parts: string[] = [`  ${s.label}`];
      if (s.areaSqft != null) parts.push(`${s.areaSqft.toFixed(1)} sqft`);
      if (s.materialType) parts.push(s.materialType);
      if (s.damagePresent) parts.push(`DAMAGED: ${s.damageType ?? 'type not specified'}`);
      lines.push(parts.join(' | '));
    }
  }

  const sidingFacets = children.sidingFacets ?? [];
  if (sidingFacets.length > 0) {
    lines.push('');
    lines.push('SIDING FACETS:');
    for (const sf of sidingFacets) {
      const wrb = sf.wrbPresent === true ? 'present' : sf.wrbPresent === false ? 'absent' : 'undetermined';
      lines.push(`  ${sf.label ?? 'Facet'} — damage: ${sf.damageType ?? 'none'} — WRB: ${wrb}`);
    }
  }

  const damageInstances = children.damageInstances ?? [];
  if (damageInstances.length > 0) {
    lines.push('');
    lines.push(`DAMAGE INSTANCES: ${damageInstances.length} documented`);
    const byType = new Map<string, number>();
    for (const d of damageInstances) {
      const t = d.instanceType ?? 'unknown';
      byType.set(t, (byType.get(t) ?? 0) + 1);
    }
    for (const [t, count] of byType) lines.push(`  ${t}: ${count}`);
  }

  const testSquares = children.testSquares ?? [];
  const testHits = children.testSquareHits ?? [];
  if (testSquares.length > 0) {
    lines.push('');
    lines.push(`TEST SQUARES: ${testSquares.length} square(s), ${testHits.length} total hit(s)`);
  }

  const products = children.products ?? [];
  if (products.length > 0) {
    lines.push('');
    lines.push('PRODUCT IDENTIFICATION:');
    for (const p of products) {
      const name = [p.brand, p.productLine].filter(Boolean).join(' ') || 'Unidentified';
      lines.push(`  ${name} — method: ${p.identificationMethod ?? 'not specified'}`);
      if (p.itelSampleRef) lines.push(`    ITEL sample: ${p.itelSampleRef}`);
    }
  }

  const interiorObs = children.interiorObservations ?? [];
  if (interiorObs.length > 0) {
    lines.push('');
    lines.push('INTERIOR / ATTIC OBSERVATIONS:');
    for (const obs of interiorObs) {
      if (obs.location || obs.description) {
        lines.push(`  ${obs.location ?? ''}: ${obs.description ?? ''}`);
      }
    }
  }

  const ra = inspection.repairabilityAssessment as StoredRepairabilityAssessment | null;
  if (ra) {
    lines.push('');
    lines.push('REPAIRABILITY ASSESSMENT:');
    if (ra.version === 2) {
      for (const system of ['roof', 'siding'] as const) {
        const flow = ra[system];
        if (!flow) continue;
        lines.push(`  ${system}: ${DETERMINATION_LABELS[flow.determination] ?? flow.determination}`);
      }
    } else if (ra.version === 3) {
      const v3 = ra as unknown as { warranted?: string };
      lines.push(`  Warranted: ${RAP_WARRANTED_LABELS[v3.warranted ?? ''] ?? v3.warranted}`);
      const rap = extractRap(ra);
      if (rap) {
        for (const line of rapScorecardBriefLines(computeRapScorecard(rap), rap.selection)) {
          lines.push(`  ${line}`);
        }
      }
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Per-section prompt builders
// ---------------------------------------------------------------------------

function buildFindingsPrompt(brief: string): string {
  return `You are writing the Damage Findings section of a forensic roofing inspection report.

${CONTRACTOR_LANE_POLICY}

Based on the field record below, produce an HTML fragment describing the documented damage findings per area. Use <h3> for area headings (e.g. "Roof System", "Siding", "Interior / Attic", "Collateral"). Under each heading, use <ul><li> items for individual findings. Each finding should state only what the field record documents — do not speculate or extrapolate.

Use only attributable phrasing:
- "The inspection documentation identifies…"
- "Photographs in this package depict…"
- "The field record documents…"

Return ONLY a valid HTML fragment. No <html>, <head>, <body> wrapper. No markdown fences. No preamble.

FIELD RECORD:
${brief}`;
}

function buildCausationPrompt(
  brief: string,
  filteredDetriments: Array<{
    entryKey: string;
    statement: string;
    requiredSupport?: string | null;
    limitation?: string | null;
  }>,
): string {
  const detrimentBlock =
    filteredDetriments.length === 0
      ? '(No applicable detriment entries for this field record.)'
      : filteredDetriments
          .map(
            (d) =>
              `Entry ${d.entryKey}:\n  Statement: ${d.statement}${d.requiredSupport ? `\n  Required support: ${d.requiredSupport}` : ''}${d.limitation ? `\n  Limitation: ${d.limitation}` : ''}`,
          )
          .join('\n\n');

  return `You are writing the Causation section of a forensic roofing inspection report.

${CONTRACTOR_LANE_POLICY}

The following detriment entries have been pre-filtered by an applicability check against the field record conditions. Apply ONLY these entries — do not reference conditions or detriments not supported by the field record. For each entry, write prose connecting the documented field conditions to the claimed detriment mechanism. Cite only what the record supports.

APPLICABLE DETRIMENT ENTRIES:
${detrimentBlock}

FIELD RECORD:
${brief}

Return ONLY a valid HTML fragment (no wrapper tags, no markdown).`;
}

function buildDetrimentApplicationPrompt(
  brief: string,
  filteredDetriments: Array<{
    entryKey: string;
    statement: string;
    requiredSupport?: string | null;
    limitation?: string | null;
  }>,
): string {
  const detrimentBlock =
    filteredDetriments.length === 0
      ? '(No applicable detriment entries for this field record.)'
      : filteredDetriments
          .map(
            (d) =>
              `Entry ${d.entryKey}:\n  Statement: ${d.statement}${d.requiredSupport ? `\n  Required support: ${d.requiredSupport}` : ''}${d.limitation ? `\n  Limitation: ${d.limitation}` : ''}`,
          )
          .join('\n\n');

  return `You are writing the Detriment Application section of a forensic roofing inspection report.

${CONTRACTOR_LANE_POLICY}

For each applicable detriment entry below:
1. Confirm the required support documentation is present in the field record (state which record element satisfies it)
2. Render the detriment statement in professional report prose, attributed to the documented record
3. Note any limitations

Present each entry as a titled subsection (<h3> with the entry key) followed by prose.

APPLICABLE DETRIMENT ENTRIES:
${detrimentBlock}

FIELD RECORD:
${brief}

Return ONLY a valid HTML fragment (no wrapper tags, no markdown).`;
}

export function buildRepairabilityProtocolNarrativePrompt(
  brief: string,
  rapMode: string | null,
  rapBriefLines: string[],
  protocols: { hasRap: boolean; hasVap: boolean; hasAsp: boolean },
): string {
  const modeInstruction = protocols.hasRap && protocols.hasAsp
    ? `This record contains both a RAP and an ASP. Describe them under separate, clearly labeled paragraphs: the Repair Attempt Protocol record may describe only its documented roof work; the Aluminum Siding Forensic Inspection Protocol must be described only as documented non-destructive observations and compatibility assessment. Never transfer RAP manipulation language to ASP, and never state or imply panel removal, component manipulation, coating cuts, fastener tests, or interlock tests for ASP.`
    : protocols.hasRap
    ? rapMode === 'fallback_slope'
      ? `The RAP was performed using the FALLBACK-SLOPE variant (the target slope did not receive a simulated repair attempt; a representative fallback slope was used). Render only the documented RAP record.`
      : rapMode === 'damaged_target'
        ? `The RAP was performed using the DAMAGED-TARGET variant (the simulated repair was applied directly to the storm-damaged area). Render only the documented RAP record.`
        : `Describe the documented RAP record only.`
    : protocols.hasAsp
      ? `This is an ASP-only record. Call it the Aluminum Siding Forensic Inspection Protocol and describe only the documented non-destructive observations and compatibility assessment. Do not name or describe a Repair Attempt Protocol.`
      : protocols.hasVap
        ? `This is a vinyl assessment record. Describe only the documented Vinyl Assessment Protocol record. Do not name or describe a Repair Attempt Protocol.`
        : `Describe only the documented repairability protocol record.`;

  return `You are writing the Repairability Protocol Narrative section of a forensic inspection report.

${CONTRACTOR_LANE_POLICY}

${modeInstruction}

Write professional prose describing only the protocol records documented below — their recorded conditions, observations, and results. Do not add conclusions beyond what the scorecard documents. If Aluminum Siding Forensic Inspection Protocol (ASP) data is present, describe it as non-destructive observation and compatibility work only; never state or imply panel removal, component manipulation, coating cuts, fastener tests, or interlock tests. Use <p> for paragraphs.

PROTOCOL SCORECARD DATA:
${rapBriefLines.join('\n')}

FIELD RECORD CONTEXT:
${brief}

Return ONLY a valid HTML fragment (no wrapper tags, no markdown).`;
}

function buildEstimateJustificationsPrompt(
  brief: string,
  estimateLines: Array<{
    description: string;
    qty: number;
    unit: string | null;
    unitPriceCents: number;
    isAdder: boolean;
  }>,
): string {
  const lineBlock =
    estimateLines.length === 0
      ? '(No estimate lines recorded.)'
      : estimateLines
          .map(
            (l, i) =>
              `Line ${i + 1}: ${l.description} — ${l.qty} ${l.unit ?? 'EA'} @ $${(l.unitPriceCents / 100).toFixed(2)}${l.isAdder ? ' [adder]' : ''}`,
          )
          .join('\n');

  return `You are writing the Estimate Justifications section of a forensic roofing inspection report.

${CONTRACTOR_LANE_POLICY}

For each estimate line item below, write 1–2 sentences explaining why this item is required based on the field record. Reference only what the documented conditions support. Use the exact line description as the heading for each justification block.

Format each justification as: <div class="est-justification"><h4>[Line description]</h4><p>[Justification]</p></div>

ESTIMATE LINES:
${lineBlock}

FIELD RECORD CONTEXT:
${brief}

Return ONLY a valid HTML fragment (no wrapper tags, no markdown).`;
}

function buildSummaryOfFindingsPrompt(
  brief: string,
  approvedSections: Map<string, string>,
): string {
  const sectionTexts: string[] = [];
  const order: Array<[string, string]> = [
    ['findings', 'Damage Findings'],
    ['causation', 'Causation'],
    ['detriment_application', 'Detriment Application'],
    ['rap_narrative', 'Repairability Protocol Narrative'],
    ['estimate_justifications', 'Estimate Justifications'],
  ];
  for (const [key, label] of order) {
    const html = approvedSections.get(key);
    if (html) {
      // Strip HTML tags to plain text for the prompt
      const text = html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 2000);
      sectionTexts.push(`${label.toUpperCase()}:\n${text}`);
    }
  }

  return `You are writing the Summary of Findings section of a forensic roofing inspection report.

${CONTRACTOR_LANE_POLICY}

Synthesize the following approved section content into a concise executive summary of 3–5 paragraphs. This section MUST:
- Only summarize what the approved sections document — do not introduce new analysis
- Present findings in a clear, professional narrative flow
- Use attributable phrasing throughout ("The inspection documentation identifies…")

APPROVED SECTIONS TO SYNTHESIZE:
${sectionTexts.join('\n\n---\n\n')}

PROPERTY CONTEXT:
${brief.split('\n').slice(0, 10).join('\n')}

Return ONLY a valid HTML fragment (no wrapper tags, no markdown).`;
}

function buildClosingStatementPrompt(
  brief: string,
  triggerFlags: Record<string, string> | null,
): string {
  const flagLines = triggerFlags
    ? Object.entries(triggerFlags)
        .map(([k, v]) => `  ${k}: ${v}`)
        .join('\n')
    : '  (No trigger flags stored — use field record conditions)';

  return `You are writing the Closing Statement section of a forensic roofing inspection report.

${CONTRACTOR_LANE_POLICY}

Write a professional closing statement (2–3 paragraphs) for this forensic inspection report. The closing should:
- Affirm what the package documents (methodology, findings, repairability assessment)
- Reference the inspector's attestation and the completeness of the photographic record
- Conditionally include relevant notes based on trigger flags below:
  * If claim_posture = pre_claim: note this is a pre-submission forensic record
  * If discontinued_status = discontinued_verified: note the product identification result is on file
  * If interior_scope_present: note interior observations are documented in the package
  * If mitigation_performed: reference the documented temporary repair/mitigation

TRIGGER FLAGS:
${flagLines}

PROPERTY CONTEXT:
${brief.split('\n').slice(0, 10).join('\n')}

Return ONLY a valid HTML fragment (no wrapper tags, no markdown).`;
}

// ---------------------------------------------------------------------------
// IICRC citation placeholder helpers
// ---------------------------------------------------------------------------

/**
 * Token pattern the generator embeds for each human-entered standards entry.
 * The UI parses these tokens and renders fill-in forms; approval is blocked
 * while any unfilled token remains in the section content.
 */
export const IICRC_PLACEHOLDER_RE = /\{\{IICRC_CITATION_PLACEHOLDER:([A-Z0-9_-]+)\}\}/g;

/**
 * Build the placeholder directive block injected into every prompt when at
 * least one standards entry has `humanEnteredProvisionsOnly = true`.
 * The AI is instructed to emit the token verbatim — never reproduce licensed
 * IICRC provision text.
 */
function buildIicrcDirectiveBlock(iicrcEntryKeys: string[]): string {
  if (iicrcEntryKeys.length === 0) return '';
  const tokens = iicrcEntryKeys
    .map((k) => `  {{IICRC_CITATION_PLACEHOLDER:${k}}}`)
    .join('\n');
  return `
IICRC CITATION PROTOCOL (MANDATORY):
The following IICRC standards are referenced for this claim. Their licensed provision text must NOT be reproduced, paraphrased, or summarized. Where you would normally cite these standards, insert the exact placeholder token shown below and nothing else:
${tokens}
Do not write any IICRC, S500, S520, or IICRC-standard content. Insert only the token.
`.trim();
}

/**
 * Extract all IICRC placeholder keys still present (unfilled) in a content string.
 */
export function extractUnfilledIicrcPlaceholders(content: string): string[] {
  const keys: string[] = [];
  let m: RegExpExecArray | null;
  const re = new RegExp(IICRC_PLACEHOLDER_RE.source, 'g');
  while ((m = re.exec(content)) !== null) {
    if (m[1] && !keys.includes(m[1])) keys.push(m[1]);
  }
  return keys;
}

// ---------------------------------------------------------------------------
// Main export types
// ---------------------------------------------------------------------------

export interface DetrimentEntryInput {
  entryKey: string;
  statement: string;
  requiredSupport?: string | null;
  limitation?: string | null;
  applicabilityConditions: unknown;
}

export interface StandardsEntryInput {
  entryKey: string;
  verificationStatus: string;
  version: number;
  verifiedAt?: Date | null;
  /** True for entries whose provision text is human-authored under a licensed
   * standard (e.g. IICRC S500/S520) and must not be reproduced by the AI
   * prompt. The generation worker must filter these out of prompt context and
   * emit a citation placeholder token for human completion. */
  humanEnteredProvisionsOnly?: boolean;
}

export interface BoilerplateVersionInput {
  sectionKey: string;
  version: number;
}

export interface AhjPackVersionInput {
  packType: string;
  version: number;
}

export interface SectionGenerationInput {
  inspectionId: string;
  sectionType: GeneratableSectionType;
  inspection: Record<string, unknown>;
  children: Parameters<typeof buildFieldBrief>[1] & {
    testSquares?: { id: string }[];
    testSquareHits?: { hitType?: string | null }[];
  };
  detrimentEntries: DetrimentEntryInput[];
  approvedSections: Map<string, string>; // sectionType → contentHtml (for DAG-last)
  standardsEntries: StandardsEntryInput[];
  boilerplateVersions: BoilerplateVersionInput[];
  ahjPackVersions: AhjPackVersionInput[];
}

export interface SectionGenerationResult {
  contentHtml: string;
  lintResult: LintResult;
  rapMode: string | null;
  libraryVersionSnapshot: {
    bpVersions: Record<string, number>;
    ahjPackVersions: Record<string, number>;
    standardsEntryKeys: string[];
    generatedAt: string;
  };
}

// ---------------------------------------------------------------------------
// Main generation function
// ---------------------------------------------------------------------------

export async function generateSectionContent(
  input: SectionGenerationInput,
): Promise<SectionGenerationResult> {
  const {
    sectionType,
    inspection,
    children,
    detrimentEntries,
    approvedSections,
    standardsEntries,
    boilerplateVersions,
    ahjPackVersions,
  } = input;

  const brief = buildFieldBrief(inspection, children);
  const conditionSet = buildFieldConditionSet(inspection, children);
  const filteredDetriments = filterDetrimentEntries(detrimentEntries, conditionSet);

  // ── IICRC filter ──────────────────────────────────────────────────────────
  // Partition standards entries: IICRC-licensed entries must never be fed to
  // the AI as citation text. Instead we build a directive that instructs the
  // AI to emit a placeholder token wherever it would cite those standards.
  const iicrcEntryKeys = standardsEntries
    .filter((e) => e.humanEnteredProvisionsOnly === true)
    .map((e) => e.entryKey);
  const iicrcDirective = buildIicrcDirectiveBlock(iicrcEntryKeys);

  let rapMode: string | null = null;
  const ra = inspection.repairabilityAssessment as StoredRepairabilityAssessment | null;
  if (ra) {
    const rapData = extractRap(ra);
    if (rapData) {
      rapMode = rapData.selection?.mode ?? null;
    }
  }

  // Build section-specific prompt, then append the IICRC directive when needed.
  let prompt: string;
  switch (sectionType) {
    case 'findings':
      prompt = buildFindingsPrompt(brief);
      break;

    case 'causation':
      prompt = buildCausationPrompt(brief, filteredDetriments);
      break;

    case 'detriment_application':
      prompt = buildDetrimentApplicationPrompt(brief, filteredDetriments);
      break;

    case 'rap_narrative': {
      const rapBrief: string[] = [];
      let hasRap = false;
      let hasVap = false;
      let hasAsp = false;
      if (ra) {
        const rapData = extractRap(ra);
        if (rapData) {
          hasRap = true;
          for (const line of rapScorecardBriefLines(computeRapScorecard(rapData), rapData.selection)) {
            rapBrief.push(line);
          }
        }
        const vapData = extractVap(ra);
        if (vapData) {
          hasVap = true;
          for (const line of vapScorecardBriefLines(computeVapScorecard(vapData))) {
            rapBrief.push(line);
          }
        }
        const aspData = extractAsp(ra);
        if (aspData) {
          hasAsp = true;
          for (const line of aspScorecardBriefLines(computeAspScorecard(aspData))) {
            rapBrief.push(line);
          }
        }
      }
      prompt = buildRepairabilityProtocolNarrativePrompt(brief, rapMode, rapBrief, {
        hasRap,
        hasVap,
        hasAsp,
      });
      break;
    }

    case 'estimate_justifications': {
      const estimate = inspection.estimate as
        | { lines?: Array<{ description?: string; quantity?: number; unit?: string | null; unitPriceCents?: number; isAdder?: boolean }> }
        | null;
      const lines = (estimate?.lines ?? []).map((l) => ({
        description: l.description ?? 'Line item',
        qty: l.quantity ?? 1,
        unit: l.unit ?? null,
        unitPriceCents: l.unitPriceCents ?? 0,
        isAdder: l.isAdder ?? false,
      }));
      prompt = buildEstimateJustificationsPrompt(brief, lines);
      break;
    }

    case 'summary_of_findings':
      prompt = buildSummaryOfFindingsPrompt(brief, approvedSections);
      break;

    case 'closing_statement': {
      const flags = inspection.triggerFlags as Record<string, string> | null;
      prompt = buildClosingStatementPrompt(brief, flags);
      break;
    }

    default:
      throw new Error(`Unknown section type: ${sectionType as string}`);
  }

  // Append IICRC directive after the main prompt body (before the final
  // "Return ONLY…" instruction so the model reads it last).
  if (iicrcDirective) {
    prompt = prompt.replace(
      /\nReturn ONLY a valid HTML fragment \(no wrapper tags, no markdown\)\./,
      `\n${iicrcDirective}\n\nReturn ONLY a valid HTML fragment (no wrapper tags, no markdown).`,
    );
    // If the replace didn't match (shouldn't happen), just append.
    if (!prompt.includes(iicrcDirective)) {
      prompt = `${prompt}\n\n${iicrcDirective}`;
    }
  }

  // Call Gemini
  const response = await geminiAi.models.generateContent({
    model: 'gemini-2.5-flash',
    contents: [{ role: 'user', parts: [{ text: prompt }] }],
    config: { maxOutputTokens: 4096 },
  });

  const rawHtml = (response.text ?? '').replace(/^```html\s*/i, '').replace(/\s*```$/, '').trim();

  // Sanitize LLM output — treat as untrusted to prevent prompt-injection XSS.
  // Placeholder tokens ({{IICRC_CITATION_PLACEHOLDER:...}}) are plain text
  // inside HTML text nodes and survive sanitization unchanged.
  const contentHtml = sanitizeSectionHtml(rawHtml);

  // Contractor-lane lint
  const lintInputs: LintFragmentInput[] = [
    {
      fragmentRef: `section.${sectionType}`,
      contentClass: 'construction_fact',
      text: contentHtml,
      isHtml: true,
    },
  ];
  const lintResult = lintReportFragments(lintInputs);

  // ── IICRC placeholder lint findings ────────────────────────────────────────
  // Any unfilled {{IICRC_CITATION_PLACEHOLDER:KEY}} token in the sanitized
  // output surfaces as a `needs_review` lint finding. The UI uses these to
  // block the Approve button until the reviewer fills in every placeholder.
  const unfilledKeys = extractUnfilledIicrcPlaceholders(contentHtml);
  for (const key of unfilledKeys) {
    lintResult.findings.push({
      fragmentRef: `section.${sectionType}`,
      ruleId: 'iicrc_citation_unfilled',
      matchedText: `{{IICRC_CITATION_PLACEHOLDER:${key}}}`,
      severity: 'needs_review',
    });
    if (lintResult.lintStatus === 'passed') {
      lintResult.lintStatus = 'needs_review';
    }
  }

  // Build library version snapshot for auditability
  const bpVersions: Record<string, number> = {};
  for (const bp of boilerplateVersions) bpVersions[bp.sectionKey] = bp.version;

  const ahjPackVersionsRecord: Record<string, number> = {};
  for (const p of ahjPackVersions) ahjPackVersionsRecord[p.packType] = p.version;

  // Collect standards entry keys referenced in the generated content.
  // Include both heuristic-matched keys from normal entries AND IICRC placeholder
  // keys (which appear as tokens, not as the raw key string in the HTML).
  const referencedStandardsKeys = standardsEntries
    .filter(
      (e) =>
        rawHtml.toLowerCase().includes(e.entryKey.toLowerCase()) ||
        (e.humanEnteredProvisionsOnly === true && unfilledKeys.includes(e.entryKey)),
    )
    .map((e) => e.entryKey);

  return {
    contentHtml,
    lintResult,
    rapMode,
    libraryVersionSnapshot: {
      bpVersions,
      ahjPackVersions: ahjPackVersionsRecord,
      standardsEntryKeys: referencedStandardsKeys,
      generatedAt: new Date().toISOString(),
    },
  };
}

// ---------------------------------------------------------------------------
// Section assembly — for the compile route to build the combined HTML
// ---------------------------------------------------------------------------

const SECTION_LABELS: Record<string, string> = {
  findings: 'Damage Findings',
  causation: 'Causation Analysis',
  detriment_application: 'Detriment Application',
  // The persisted key is retained for backwards compatibility, but this
  // narrative can cover RAP, VAP, ASP, or a documented combination.
  rap_narrative: 'Repairability Protocol Narrative',
  estimate_justifications: 'Estimate Justifications',
  summary_of_findings: 'Summary of Findings',
  closing_statement: 'Closing Statement',
};

const SECTION_ORDER: string[] = [
  'findings',
  'causation',
  'detriment_application',
  'rap_narrative',
  'estimate_justifications',
  'summary_of_findings',
  'closing_statement',
];

export interface LockedSectionRow {
  sectionType: string;
  contentHtml: string | null;
  lockedAt: Date | null;
  lockedBy: string | null;
  libraryVersionSnapshot: unknown;
}

/**
 * Assembles locked section content into a single HTML document with a TOC.
 * Two-pass: collect section headings, then build TOC block, then assemble body.
 */
export function assembleSectionHtml(lockedSections: LockedSectionRow[]): string {
  const byType = new Map(lockedSections.map((s) => [s.sectionType, s]));

  // First pass: collect sections in order
  const sectionBlocks: Array<{ id: string; label: string; html: string }> = [];
  for (const key of SECTION_ORDER) {
    const row = byType.get(key);
    if (!row || !row.contentHtml) continue;
    sectionBlocks.push({
      id: `section-${key.replace(/_/g, '-')}`,
      label: SECTION_LABELS[key] ?? key,
      html: row.contentHtml,
    });
  }

  if (sectionBlocks.length === 0) return '';

  // Second pass: build TOC
  const tocItems = sectionBlocks
    .map((b) => `<li><a href="#${b.id}">${b.label}</a></li>`)
    .join('\n  ');
  const toc = `<nav class="section-toc" aria-label="Table of Contents">
  <h2>Contents</h2>
  <ol>
  ${tocItems}
  </ol>
</nav>`;

  // Assemble body with anchor IDs
  const body = sectionBlocks
    .map(
      (b) =>
        `<section id="${b.id}" class="report-section">
<h2>${b.label}</h2>
${b.html}
</section>`,
    )
    .join('\n\n');

  return `${toc}\n\n${body}`;
}
