import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import companiesRouter from "./companies";
import storageRouter from "./storage";
import profileRouter from "./profile";
import pinsRouter from "./pins";
import adminRouter from "./admin";
import locationRouter from "./location";
import geocodeRouter from "./geocode";
import inspectionsRouter from "./inspections";
import canvassingRouter from "./canvassing";
import activityRouter from "./activity";
import weatherRouter from "./weather";
import crmRouter from "./crm";
import bugReportsRouter from "./bugReports";
import priceBookRouter from "./priceBook";
import discontinuedProductsRouter from "./discontinuedProducts";
import agreementRouter from "./agreement";
import portalRouter from "./portal";
import libraryRouter from "./library";
import ahjWizardRouter from "./ahjWizard";
import pipelineEventsRouter from "./pipelineEvents";
import dashboardRouter from "./dashboard";
import templatesRouter from "./templates";
import paymentsRouter from "./payments";
import invoicesRouter from "./invoices";
import expensesRouter from "./expenses";
import changeOrdersRouter from "./changeOrders";
import profitabilityRouter from "./profitability";
import financialsExportRouter from "./financialsExport";
import insuranceRouter from "./insurance";
import selectionsRouter from "./selections";
import contractsRouter from "./contracts";
import contractPortalRouter from "./contractPortal";
import calendarRouter from "./calendar";
import notificationsRouter from "./notifications";
import completionCertificatesRouter from "./completionCertificates";
import betaApplyRouter from "./betaApply";
import trialRouter from "./trial";
import pricingRouter from "./pricing";
import trialAdminRouter from "./trialAdmin";
import ppRouter from "./pp";
import ppAdminRouter from "./ppAdmin";
import builderRouter from "./builder";
import ahjMasterRouter from "./ahjMaster";
import devRouter from "./dev";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(companiesRouter);
router.use(storageRouter);
router.use(profileRouter);
router.use(pinsRouter);
router.use(adminRouter);
router.use(locationRouter);
router.use(geocodeRouter);
router.use(inspectionsRouter);
router.use(canvassingRouter);
router.use(activityRouter);
router.use(weatherRouter);
router.use(crmRouter);
router.use(bugReportsRouter);
router.use(priceBookRouter);
router.use(discontinuedProductsRouter);
router.use(agreementRouter);
router.use(portalRouter);
router.use(libraryRouter);
router.use(ahjWizardRouter);
router.use(pipelineEventsRouter);
router.use(dashboardRouter);
router.use(templatesRouter);
router.use(paymentsRouter);
router.use(invoicesRouter);
router.use(expensesRouter);
router.use(changeOrdersRouter);
router.use(profitabilityRouter);
router.use(financialsExportRouter);
router.use(insuranceRouter);
router.use(selectionsRouter);
router.use(contractsRouter);
router.use(contractPortalRouter);
router.use(calendarRouter);
router.use(notificationsRouter);
router.use(completionCertificatesRouter);
router.use(betaApplyRouter);
router.use(trialRouter);
router.use(pricingRouter);
router.use(trialAdminRouter);
router.use(ppRouter);
router.use(ppAdminRouter);
router.use(builderRouter);
router.use(ahjMasterRouter);
router.use(devRouter);

export default router;
