-- Migration 004: void support for signed_agreements
--
-- 1. Drop the old full unique constraint on inspection_id (one agreement per
--    inspection). Voided rows must no longer block a replacement signing.
-- 2. Add the three void columns (nullable — null means "not voided").
-- 3. Recreate uniqueness as a PARTIAL index that only covers active
--    (non-voided) rows, so at most one active agreement can exist per
--    inspection while an arbitrary number of voided rows are allowed.
--
-- Safe to re-run: DROP IF EXISTS / ADD COLUMN IF NOT EXISTS / CREATE UNIQUE
-- INDEX IF NOT EXISTS are all idempotent.

-- 1. Drop old unique constraint (name generated by Postgres from table+column).
--    Tolerate the case where it has already been dropped.
DO $$
BEGIN
  ALTER TABLE signed_agreements DROP CONSTRAINT IF EXISTS signed_agreements_inspection_id_unique;
EXCEPTION WHEN others THEN
  NULL;
END;
$$;

-- 2. Add void columns (idempotent).
ALTER TABLE signed_agreements
  ADD COLUMN IF NOT EXISTS voided_at       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS voided_by_user_id VARCHAR REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS void_reason     TEXT;

-- 3. Partial unique index: only one active (non-voided) agreement per inspection.
CREATE UNIQUE INDEX IF NOT EXISTS signed_agreements_inspection_id_active_uniq
  ON signed_agreements (inspection_id)
  WHERE voided_at IS NULL;
